// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mxecbagyjxpuhjjilzlc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14ZWNiYWd5anhwdWhqamlsemxjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMTEzNjUsImV4cCI6MjA3MDY4NzM2NX0.L4G2x2ECYyvuqgULtT7X0YhXSrDq7XkWPs8HVazcK7I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});